name: Refresh dashboard data

on:
  schedule:
    - cron: "0 * * * *" # hourly UTC
  workflow_dispatch:

jobs:
  build-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: refresh-data
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Reset to latest main
        run: |
          git fetch origin
          git reset --hard origin/main
          git status

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyarrow

      # Build writes docs/data_build/*.csv, manifest.csv, version.json and exits
      - name: Build data artifacts
        env:
          DASHBOARD_BUILD: "1"
          BLS_API_KEY: ${{ secrets.BLS_API_KEY }}
        run: python scripts/build_artifacts.py

      # Sanity output
      - name: Show manifest preview
        run: |
          echo "Top of docs/data_build/manifest.csv:"
          head -n 10 docs/data_build/manifest.csv || true
          echo "Version file:"
          cat docs/data_build/version.json || true

      # Commit & push all changes, including renames/deletions
      - name: Commit updated artifacts to Pages folder
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A docs/data_build
          git commit -m "chore(data): refresh artifacts [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
